package org.funfix.delayedqueue.jvm.internals.jdbc.oracle

import org.funfix.delayedqueue.jvm.internals.jdbc.Migration

/** Oracle-specific migrations for the DelayedQueue table. */
internal object OracleMigrations {
    /**
     * Gets the list of migrations for Oracle.
     *
     * @param tableName The name of the delayed queue table
     * @return List of migrations in order
     */
    fun getMigrations(tableName: String): List<Migration> =
        listOf(
            Migration.createTableIfNotExists(
                tableName = tableName,
                sql =
                    """
                    CREATE TABLE "$tableName" (
                        "id" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "pKey" VARCHAR2(200) NOT NULL,
                        "pKind" VARCHAR2(100) NOT NULL,
                        "payload" BLOB NOT NULL,
                        "scheduledAt" NUMBER(19) NOT NULL,
                        "scheduledAtInitially" NUMBER(19) NOT NULL,
                        "lockUuid" VARCHAR2(36) NULL,
                        "createdAt" NUMBER(19) NOT NULL
                    );

                    CREATE UNIQUE INDEX "${tableName}__PKeyPlusKindUniqueIndex"
                    ON "$tableName"("pKey", "pKind");

                    CREATE INDEX "${tableName}__KindPlusScheduledAtIndex"
                    ON "$tableName"("pKind", "scheduledAt", "id");

                    CREATE INDEX "${tableName}__LockUuidPlusIdIndex"
                    ON "$tableName"("lockUuid", "id");
                    """,
            ),
            // Migration 2: Update index to include 'id' column for deterministic ordering
            Migration(
                sql =
                    """
                    BEGIN
                        EXECUTE IMMEDIATE 'DROP INDEX "${tableName}__KindPlusScheduledAtIndex"';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -1418 THEN
                                RAISE;
                            END IF;
                    END;
                    /
                    CREATE INDEX "${tableName}__KindPlusScheduledAtIndex"
                    ON "$tableName"("pKind", "scheduledAt", "id");
                    """,
                needsExecution = { conn ->
                    // Check if index exists but doesn't have the 'id' column
                    val metadata = conn.underlying.metaData
                    var hasIndex = false
                    var hasIdColumn = false
                    
                    metadata.getIndexInfo(null, null, tableName, false, false).use { rs ->
                        while (rs.next()) {
                            val indexName = rs.getString("INDEX_NAME")
                            if (indexName == "${tableName}__KindPlusScheduledAtIndex") {
                                hasIndex = true
                                val columnName = rs.getString("COLUMN_NAME")
                                val ordinalPosition = rs.getShort("ORDINAL_POSITION")
                                // Check if 'id' is in position 3
                                if (columnName == "id" && ordinalPosition == 3.toShort()) {
                                    hasIdColumn = true
                                }
                            }
                        }
                    }
                    
                    // Run migration if index exists but doesn't have id column
                    hasIndex && !hasIdColumn
                },
            ),
        )
}
